
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import Nodos.NodoListaDoble;
import Objetos.Usuario;
import Nucleo.Estructuras;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class UsersParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symUsers.class;
}

  /** Default constructor. */
  @Deprecated
  public UsersParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public UsersParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public UsersParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\004\000\002\002\004\000\002\002" +
    "\002\000\002\003\006\000\002\004\005\000\002\004\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\006\002\uffff\004\004\001\002\000\004\007" +
    "\011\001\002\000\006\002\uffff\004\004\001\002\000\004" +
    "\002\007\001\002\000\004\002\001\001\002\000\004\002" +
    "\000\001\002\000\004\005\012\001\002\000\006\006\ufffc" +
    "\010\015\001\002\000\004\006\014\001\002\000\006\002" +
    "\ufffe\004\ufffe\001\002\000\004\005\012\001\002\000\004" +
    "\006\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\006\002\007\003\004\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\012\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\015\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$UsersParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$UsersParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$UsersParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    Usuario user = new Usuario();
    public UsersParser(UsersLexer lex){
        super(lex);
    }

    @Override
    public void syntax_error(Symbol st) {
        Token error = (Token) st.value;
        report_error("Error Sintactico con el Token:"+ error.getLexeme()+" este no pertenece a la estructura  >linea: "+error.getLine()+" >columna: "+error.getColumn() + "\n",null);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$UsersParser$actions {
  private final UsersParser parser;

  /** Constructor */
  CUP$UsersParser$actions(UsersParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$UsersParser$do_action_part00000000(
    int                        CUP$UsersParser$act_num,
    java_cup.runtime.lr_parser CUP$UsersParser$parser,
    java.util.Stack            CUP$UsersParser$stack,
    int                        CUP$UsersParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$UsersParser$result;

      /* select the action based on the action number */
      switch (CUP$UsersParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= s0 EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-1)).value;
		RESULT = start_val;
              CUP$UsersParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-1)), ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$UsersParser$parser.done_parsing();
          return CUP$UsersParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // s0 ::= s1 s0 
            {
              Object RESULT =null;

              CUP$UsersParser$result = parser.getSymbolFactory().newSymbol("s0",0, ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-1)), ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()), RESULT);
            }
          return CUP$UsersParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // s0 ::= 
            {
              Object RESULT =null;

              CUP$UsersParser$result = parser.getSymbolFactory().newSymbol("s0",0, ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()), RESULT);
            }
          return CUP$UsersParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // s1 ::= ID DOSPUNTOS s2 PUNTOCOMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-3)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-3)).value;
		
        Usuario nuevoUser = user;
        nuevoUser.setId(id.getLexeme());
       // nuevoUser.getListaImagenes().mostrarDatos();
        Estructuras.insertarUsuario(user);
        user = new Usuario();
    
              CUP$UsersParser$result = parser.getSymbolFactory().newSymbol("s1",1, ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-3)), ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()), RESULT);
            }
          return CUP$UsersParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // s2 ::= NUMERO COMA s2 
            {
              Object RESULT =null;
		int imgleft = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-2)).left;
		int imgright = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-2)).right;
		Token img = (Token)((java_cup.runtime.Symbol) CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-2)).value;
		
        user.getListaImagenes().insertarNodo(new NodoListaDoble(Integer.parseInt(img.getLexeme())));
    
              CUP$UsersParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$UsersParser$stack.elementAt(CUP$UsersParser$top-2)), ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()), RESULT);
            }
          return CUP$UsersParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // s2 ::= NUMERO 
            {
              Object RESULT =null;
		int imgleft = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()).left;
		int imgright = ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()).right;
		Token img = (Token)((java_cup.runtime.Symbol) CUP$UsersParser$stack.peek()).value;
		
        user.getListaImagenes().insertarNodo(new NodoListaDoble(Integer.parseInt(img.getLexeme())));
    
              CUP$UsersParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$UsersParser$stack.peek()), RESULT);
            }
          return CUP$UsersParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$UsersParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$UsersParser$do_action(
    int                        CUP$UsersParser$act_num,
    java_cup.runtime.lr_parser CUP$UsersParser$parser,
    java.util.Stack            CUP$UsersParser$stack,
    int                        CUP$UsersParser$top)
    throws java.lang.Exception
    {
              return CUP$UsersParser$do_action_part00000000(
                               CUP$UsersParser$act_num,
                               CUP$UsersParser$parser,
                               CUP$UsersParser$stack,
                               CUP$UsersParser$top);
    }
}

}
