
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import Nodos.NodoListaSimple;
import Objetos.Imagen;
import Nucleo.Estructuras;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ImgParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symImg.class;
}

  /** Default constructor. */
  @Deprecated
  public ImgParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ImgParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ImgParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\004\000\002\002\004\000\002\002" +
    "\002\000\002\003\006\000\002\003\006\000\002\004\005" +
    "\000\002\004\003\000\002\005\003\000\002\005\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\010\002\uffff\004\004\005\005\001\002\000" +
    "\004\006\022\001\002\000\004\006\012\001\002\000\010" +
    "\002\uffff\004\004\005\005\001\002\000\004\002\010\001" +
    "\002\000\004\002\001\001\002\000\004\002\000\001\002" +
    "\000\006\004\014\005\013\001\002\000\006\007\ufffa\010" +
    "\ufffa\001\002\000\006\007\ufff9\010\ufff9\001\002\000\006" +
    "\007\ufffb\010\020\001\002\000\004\007\017\001\002\000" +
    "\010\002\ufffd\004\ufffd\005\ufffd\001\002\000\006\004\014" +
    "\005\013\001\002\000\004\007\ufffc\001\002\000\006\004" +
    "\014\005\013\001\002\000\004\007\024\001\002\000\010" +
    "\002\ufffe\004\ufffe\005\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\006\002\006\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\002\010\003\005\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\004\015\005\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\020\005\014\001\001\000\002\001\001" +
    "\000\006\004\022\005\014\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ImgParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ImgParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ImgParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    Imagen imagen = new Imagen();
    public ImgParser(ImgLexer lex){
        super(lex);
    }

    @Override
    public void syntax_error(Symbol st) {
        Token error = (Token) st.value;
        report_error("Error Sintactico con el Token:"+ error.getLexeme()+" este no pertenece a la estructura  >linea: "+error.getLine()+" >columna: "+error.getColumn() + "\n",null);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ImgParser$actions {
  private final ImgParser parser;

  /** Constructor */
  CUP$ImgParser$actions(ImgParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ImgParser$do_action_part00000000(
    int                        CUP$ImgParser$act_num,
    java_cup.runtime.lr_parser CUP$ImgParser$parser,
    java.util.Stack            CUP$ImgParser$stack,
    int                        CUP$ImgParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ImgParser$result;

      /* select the action based on the action number */
      switch (CUP$ImgParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= s0 EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-1)).value;
		RESULT = start_val;
              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-1)), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ImgParser$parser.done_parsing();
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // s0 ::= s1 s0 
            {
              Object RESULT =null;

              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s0",0, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-1)), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // s0 ::= 
            {
              Object RESULT =null;

              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s0",0, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // s1 ::= ID LLAVE_A s2 LLAVE_C 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)).value;
		
        Imagen nuevaImagen = imagen;
        nuevaImagen.setId(Integer.parseInt(id.getLexeme()));
        nuevaImagen.getCapas().mostrarDatos();
        Estructuras.insertarImagen(nuevaImagen);
        imagen = new Imagen();
    
              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s1",1, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // s1 ::= NUMERO LLAVE_A s2 LLAVE_C 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)).value;
		
        Imagen nuevaImagen = imagen;
        nuevaImagen.setId(Integer.parseInt(id.getLexeme()));
        nuevaImagen.getCapas().mostrarDatos();
        Estructuras.insertarImagen(nuevaImagen);
        imagen = new Imagen();
    
              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s1",1, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-3)), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // s2 ::= s3 COMA s2 
            {
              Object RESULT =null;

              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.elementAt(CUP$ImgParser$top-2)), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // s2 ::= s3 
            {
              Object RESULT =null;

              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s2",2, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // s3 ::= NUMERO 
            {
              Object RESULT =null;
		int capaleft = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()).left;
		int caparight = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()).right;
		Token capa = (Token)((java_cup.runtime.Symbol) CUP$ImgParser$stack.peek()).value;
		
        imagen.getCapas().insertarNodo(new NodoListaSimple(Integer.parseInt(capa.getLexeme())));
    
              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s3",3, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // s3 ::= ID 
            {
              Object RESULT =null;
		int capaleft = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()).left;
		int caparight = ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()).right;
		Token capa = (Token)((java_cup.runtime.Symbol) CUP$ImgParser$stack.peek()).value;
		
        imagen.getCapas().insertarNodo(new NodoListaSimple(Integer.parseInt(capa.getLexeme())));
    
              CUP$ImgParser$result = parser.getSymbolFactory().newSymbol("s3",3, ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ImgParser$stack.peek()), RESULT);
            }
          return CUP$ImgParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ImgParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ImgParser$do_action(
    int                        CUP$ImgParser$act_num,
    java_cup.runtime.lr_parser CUP$ImgParser$parser,
    java.util.Stack            CUP$ImgParser$stack,
    int                        CUP$ImgParser$top)
    throws java.lang.Exception
    {
              return CUP$ImgParser$do_action_part00000000(
                               CUP$ImgParser$act_num,
                               CUP$ImgParser$parser,
                               CUP$ImgParser$stack,
                               CUP$ImgParser$top);
    }
}

}
