
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class symCapas {
  /* terminals */
  public static final int COLOR = 3;
  public static final int COMA = 8;
  public static final int EOF = 0;
  public static final int LLAVE_C = 7;
  public static final int LLAVE_A = 6;
  public static final int NUMERO = 4;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int PUNTOCOMA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "COLOR",
  "NUMERO",
  "PUNTOCOMA",
  "LLAVE_A",
  "LLAVE_C",
  "COMA"
  };
}

